# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberBlanace',
            new_name='MemberBalance',
        ),
    ]
