# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0002_auto_20170805_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='passcode',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studygroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
