# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0003_auto_20170805_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroupsession',
            name='session_date',
            field=models.DateField(auto_created=True),
        ),
    ]
