# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroup', '0007_auto_20170805_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygrouprule',
            name='rule_amount',
            field=models.IntegerField(null=True),
        ),
    ]
